stages:
  - build

image: docker:latest

services:
  - docker:dind

variables:
  TAG_COMMIT: $DOCKERHUB_USERNAME/compose-dind:$CI_COMMIT_TAG
  TAG_LATEST: $DOCKERHUB_USERNAME/compose-dind:latest

build tag:
  stage: build
  only:
    - tags
  script:
    - echo "Building ${TAG_COMMIT}..."
    - docker pull $TAG_LATEST
    - docker build -t ${TAG_COMMIT} .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker push ${TAG_COMMIT}

build latest:
  stage: build
  only:
    - master
  script:
    - echo "Building ${TAG_LATEST}..."
    - docker pull $TAG_LATEST
    - docker build -t ${TAG_LATEST} .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker push ${TAG_LATEST}
   
